[twitter]
# Create an app at: https://developer.twitter.com/en/apps
# Then put tokens here:

# AKA: "API token"
consumerKey = ""
# AKA: "API Secret Key"
consumerSecret = ""

# AKA: "Authentication Tokens"
accessTokenKey = ""
accessTokenSecret = ""

[feoblog]
server = "http://127.0.0.1:8080"

[twitter.homeTimeline]
# This syncs the current Twitter user's home timeline (i.e.: posts from those they follow)
# from Twitter into this feoblog user's blog:
userID = ""
password = ""

# Don't bother syncing tweets/retweets/quote-tweets from these twitter users:
skipUsers = [
    "chattyMcChatterson",
]

[[twitter.userTimelines]]
twitterScreenName = "twitterName"

# Sync all tweets from the above user to a this FeoBlog user.
# Note: We use the timestamps of posts to know where to pick up sync, so
# this FeoBlog userID should contain *only* these sync'd posts:
userID = ""
password = ""

# Should we copy attachments into FeoBlog? (Default: false)
# Note: this ONLY copies attachments from $twitterScreeName, not quote tweets
# or retweets. (Those add up quick!)
copyAttachments = true

skipReplies = false # default
skipRetweets = false # default
